- shell.py
Shell의 껍데기 클래스 작성했습니다.
Command와 Config 클래스는 추후 분리하여 다른 파일로 관리하면 좋을 것 같습니다.
> [FEAT] Initial design of shell

- consts/commands.py
- consts/help_msg.py
- shell.py
consts 폴더 추가하였습니다. 
constants는 여기서 관리하면 좋을 것 같습니다~!
더 좋은 폴더 구조가 생각나시면 피드백 주시면 감사하겠습니다. 😊
> [Chore] Constant 파일 분리 및 Help message 추가

- .gitignore
- tests/test_shell.py
Test code for shell 추가 (Help, Invalid command)
> [FEAT] Add test code for basic commands in shell

- ssd.py
python 함수를 subprocess 등으로 call 할 수 있게 main 함수를 추가하였습니다.
unit 테스트 모두 통과하는 것을 확인했습니다. (수정 전: 통과 / 수정 후 : 통과)
> [FEAT] Add Main Function in SSD file to enable python-file calling.

- tests/test_shell.py
> [FEAT] add test code for test scripts in shell

- ssd.py
- tests/test_ssd.py
Test 함수 test_read_ssd_nand_txt_file_called_by_write/ test_read_method_record_ssd_output_txt/ test_write_ssd
에서 Mock 객체 사용하도록 변경하였습니다.
> [FEATURE] Test함수에서 FileManager를 Mock 객체를 사용하도록 변경.

- ssd.py
- tests/test_ssd.py
Test 함수 1~3를 FileManager에 맞게 수정하였습니다.
> [FEAT] Test함수에 FileManager를 Mock 객체를 사용하도록 변경.

- shell.py
> [FEAT] Full read in shell

- commands.py
- consts/commands.py
- shell.py
read, write 커맨드 구현 진행 중입니다. 
공동 작업을 위해 일단 개발 중 코드 공유드립니다. 
** 현재 read, write 실행 안되고 있습니다.
> [FEAT] read, write command added (not working)

- .gitignore
- commands.py
- shell.py
- ssd.py
read, write 간단한 정상 실행 테스트 완료했습니다!
fullread, fullwrite와 script들 작성 같이 해보시죠~!
> [FIX] read, write 간단한 정상 실행 테스트 완료

- shell.py
> [FEAT] Shell custom function 3

- shell.py
Script 2 작성 후 실제 SSD로 실행 테스트 완료했습니다.
> [FEAT] Script 2 작성

- shell.py
> [FEAT] Add script_1 in shell

- ssd.py
- tests/test_ssd.py
File Manager write 함수 merge 하였습니다.
- unit test 모두 통과하는 것 확인하였습니다.
> [FEATURE] FILE_MANAGER 개발 완료 

- constant.py
- shell.py
- utils.py
[REFACTOR] Refactoring naming convention in shell class
> [REFACTOR] Refactoring naming convention in shell class

- commands.py
- shell.py
Shell command의 이름에 Shell을 추가했습니다. 
SSD의 command가 생긴다면 분리해서 쓸 수 있을 것 같습니다~!
> [CHORE] Shell command의 이름에 Shell을 추가. 

- constant.py
- shell.py
ShellParser를 Shell 클래스에서 분리하여, 역할을 분리했습니다.
> [REFACTOR] Separate ShellParser from Shell class

- tests/test_ssd.py
커밋이 꼬여서 PR을 새로 생성했습니다. (all tests pass 확인하였습니다.)
> [REFACTOR] Add tests for coverate for write in FileManager

- shell.py
> [HOTFIX] helper not working fixed

- logger.py
- tests/test_logger.py
logger.py 와 test_logger.py 추가
1. format에 맞게 print
2. MAX_SIZE 보다 over 되면 새로운 파일로 rollover
> [FEATURE] Add logger.py and test_logger

- ssd.py
- tests/test_ssd.py
python .\ssd.py E [LBA] [SIZE]
ex) python .\ssd.py E 0 10 - 0번을 포함해, 10 사이즈만큼 삭제 (9까지)
실제론 삭제가 아니라, 0x00000000 이 된다.
1 <= SIZE <= 10
예외 처리
사용법에 올바르지 않는 명령 사용 (파라미터 갯수, 타입 등)
LBA 가 0 ~ 99 범위에서 벗어나거나, SIZE 가 1 미만 10 초과
SIZE 만큼 더했을 때 LBA 가 99 를 초과
> [FEATURE] SSD를 위한 UNIT TEST와 기능 추가

- constant.py
- ssd.py
> [HOTFIX] filelock 빼기

- tests/test_buffer.py
[FEAT] add more tests in buffers to increate coverity (up to 96%)
> [FEAT] add more tests in buffers to increate coverity (up to 96%)

- tests/test_shell.py
리팩토링된 shell 코드에 맞추어 테스트 코드 수정했습니다.
> [FIX] modify tests for shell to call execute_command

- tests/test_buffer.py
> [FEAT] bug fix 

- ssd.py
[FEATURE] F command 추가
[BUGFIX] E command erase size 버그 수정
> [FEATURE] F command 추가

- constant.py
- shell.py
- ssd.py
- utils.py
> [REFACTOR] Constant lba size

- ssd.py
- tests/test_ssd.py
[BUGFIX&TEST] command buffer 버그 수정 및 테스트 추가
> [BUGFIX&TEST] command buffer 버그 수정 및 테스트 추가

- ssd.py
- tests/test_ssd.py
1. F command가 들어올 때
2. Buffer가 가득 찰 때
3. F command가 들어 와 잘 된 경우 마지막에 ""를 output txt에 작성하도록 개선
> [FEATURE] Add flush test

- command_buffer.py
- tests/test_buffer.py
[FEAT] bug fix for finding strings in buffer manager.
All tests pass in test_buffer.py
> [FEAT] bug fix for finding strings in buffer manager.

- ssd.py
flush 동작 중 erase 명령 버그 수정했습니다.
> [FIX] fix ssd flush when erase command executed

- constant.py
- shell.py
- shell_script.txt
> [FEAT] Add default script

- constant.py
> [FEAT] Help message

- command_buffer.py
[REFACTOR] command_buffer 중복 코드 함수로 변경
> [REFACTOR] command_buffer 중복 코드 함수로 변경

- ssd.py
1. 코드 중복 줄이기
2. 조건문을 이해하기 쉽게 함수로 리팩터
3. 가독성 개선
test_ssd, test_shell, test_logger, test_buffer 모두 통과된 것 확인하였습니다.
> [REFACTOR] process_erase_mode 리팩토링

- tests/test_shell.py
[FEAT] add test for run function in shell
1개 더 테스트 추가했습니다. test_shell 테스트 통과 확인 완료
> [FEAT] add test for run function in shell

- buffer_manager.py
1_E_0_10 가 있을 때,
1_empty가 만들어지는 에러를 고쳤습니다.
> [FEAT] error fix.
